# based on example from 
#  - https://docs.docker.com/build/ci/github-actions/examples/
#  - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
#
# See also: 
# - https://github.com/actions/checkout
# - https://github.com/actions/cache
# - https://github.com/docker/setup-buildx-action
# 
name: build

on:
  push:
    branches: ['main']
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
  pull_request:
    branches: ['main']
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'

env:
  IMAGE-PATH: ${{ github.repository }}
  IMAGE-REGISTRY: ghcr.io
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3 

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: my_meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.IMAGE-REGISTRY }}/${{ env.IMAGE-PATH }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Login to docker repo
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ${{ env.IMAGE-REGISTRY}}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.my_meta.outputs.tags }}
        labels: ${{ steps.my_meta.outputs.labels }}
